MvcControls/MvcControls/Models/ListViewTestModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;
using System.Web;
using MvcControls.Controls;

namespace MvcControls.Models
{
    public class ListViewTestModel
    {
        [DisplayName("Die Items")]
        public List<MeinItem> MeineItems { get; set; }

        [DisplayName("Mitarbeiter")]
        public List<MeinItem> DieChicks { get; set; }

        public List<string> SelectedChicks { get; set; }

        public string Test { get; set; }

        public List<string> SelectedItems { get; set; }

        public List<string> Ruedi { get; set; }

        public string SelectionResult { get; set; }

        public ListViewTestModel()
        {
            MeineItems = new List<MeinItem>
            {
                new MeinItem(1, "Hans"),
                new MeinItem(2, "Pesche"),
                new MeinItem(3, "Ueli"),
                new MeinItem(4, "Ruedi"),
                new MeinItem(5, "Rudolf")
            };

            DieChicks = new List<MeinItem>
            {
                new MeinItem(770, "Saskia"),
                new MeinItem(501, "Janine"),
                new MeinItem(8804, "Sarah"),
                new MeinItem(5152, "Elvira"),
                new MeinItem(2, "Petra"),
                new MeinItem(99, "Julia"),
                new MeinItem(69, "Judith"),
                new MeinItem(70, "Miranda"),
                new MeinItem(71, "Melanie"),
                new MeinItem(72, "Mirella"),
                new MeinItem(73, "Marlene"),
                new MeinItem(74, "Leila")
            };
        }
    }

    [DebuggerDisplay("MeinItem: Id={Id}, IsSelected={IsSelected}")]
    public class MeinItem : ISelectable
    {
        public int Id { get; set; }
        public string Caption { get; set; }
        public bool IsSelected { get; set; }

        public MeinItem()
        {

        }

        public MeinItem(int id, string caption)
        {
            Id = id;
            Caption = caption;
        }
    }
}

MvcControls/MvcControls/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcControls.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MvcControls/MvcControls/Controllers/ListViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcControls.Models;

namespace MvcControls.Controllers
{
    public class ListViewController : Controller
    {
        // GET: ListView
        public ActionResult Index()
        {
            return View(new ListViewTestModel());
        }

        public ActionResult Test(ListViewTestModel model)
        {

            if (model.DieChicks != null)
            {
                model.SelectionResult = "Chicks: " +
                                        string.Join(",", model.DieChicks.Where(item => item.IsSelected).Select(item => item.Caption));
            }

            return View("Index", model);
        }
    }
}

MvcControls/MvcControls/Views/Home/Index.cshtml
@{
    ViewBag.Title = "MvcControls - Home";
}

<div class="jumbotron">
    <h1>MvcControls</h1>
    <p class="lead">A simple ASP.NET MVC helper that displays a ListView.</p>
</div>

MvcControls/MvcControls/Views/ListView/Index.cshtml
@using MvcControls.Controls
@model MvcControls.Models.ListViewTestModel

@{
    ViewBag.Title = "ListView Demo";
}

<h2>ListView Demo</h2>

@using (Html.BeginForm("Test", "ListView"))
{
    <div class="row">
        <div class="col-md-4">
            @Html.ListViewFor(m => m.DieChicks, showSearchField: true, showCheckAll: true)
            <span>@Model.SelectionResult</span>
        </div>
        <div class="col-md-4">
            @Html.ListViewFor(m => m.MeineItems, showSearchField: true, showCheckAll: true)
        </div>
    </div>
    
    <input type="submit" value="Submit Page" class="btn-default btn"/>
}

@Styles.Render("~/Content/ListView.css")

@section scripts
{
    @Scripts.Render("~/Scripts/listView.js")
}

MvcControls/MvcControls/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MvcControls", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("ListView", "Index", "ListView")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MvcControls</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>